title = "Eddie Jeselnik"
baseURL = 'https://jeselnik.xyz'
languageCode = 'en-au'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = false

  #footer items
  nextprev = false
  taglist = false
  showrss = true