name: deploy
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # see https://github.com/aws/aws-cli/issues/5623
  AWS_EC2_METADATA_DISABLED: true
  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
  PORKBUN_SECRET_API_KEY: ${{ secrets.PORKBUN_SECRET_API_KEY }}

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: Tofu Init
        run: tofu init
      - name: Tofu Apply
        run: tofu apply -auto-approve -no-color
  sync:
    name: Sync
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v2
      - name: Compile Site
        run: hugo
        working-directory: ./site
      - name: Sync
        run: aws s3 sync . s3://jeselnik.xyz --size-only --delete
        working-directory: ./site/public
