name: deploy
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # see https://github.com/aws/aws-cli/issues/5623
  AWS_EC2_METADATA_DISABLED: true
  CLOUDFLARE_API_TOKEN: ${{ secrets.ACTIONS_CLOUDFLARE }}
  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
  PORKBUN_SECRET_API_KEY: ${{ secrets.PORKBUN_SECRET_API_KEY }}

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: Tofu Init
        run: tofu init
      - name: Tofu Apply
        run: tofu apply -auto-approve -no-color
  sync:
    name: Sync Frontend
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v3
      - name: Compile
        run: hugo
        working-directory: ./eddie-jeselnik-xyz
      - name: Sync
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.ACTIONS_CLOUDFLARE }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy eddie-jeselnik-xyz/public --project-name=eddie-jeselnik-xyz --commit-dirty=true
  backend:
    name: Build & Deploy Backend
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build Lambda Function
        run: go build -o bootstrap main.go
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
      - name: Package Build
        run: zip backend.zip bootstrap
      - name: Upload Build to S3
        run: aws s3 cp backend.zip s3://jeselnik-xyz-lambda/
      - name: Update Lambda Code
        run: aws lambda update-function-code --function-name jeselnik-xyz-backend --s3-bucket jeselnik-xyz-lambda --s3-key backend.zip --region ap-southeast-2
