name: deploy
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # see https://github.com/aws/aws-cli/issues/5623
  AWS_EC2_METADATA_DISABLED: true

jobs:
  #terraform:
  #  name: Deploy Infrastructure
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      working-directory: ./infra
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: hashicorp/setup-terraform@v3
  #    - name: Terraform Init
  #      run: terraform init
  #    - name: Terraform Apply
  #      run: terraform apply -auto-approve
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-hugo@v2
      - name: Compile Site
        run: hugo
        working-directory: ./site
      - name: Sync
        run: aws s3 sync . s3://jeselnik.xyz --region ap-southeast-2 --size-only
        working-directory: ./site/public